spring:
  data:
    mongodb:
      database: ApnaJalPaanDB
      host: localhost
      port: 27017
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


server:
  port: 8080
